[package]
name = "rust-local"
version = "0.1.0"
authors = ["juniuszhou <junius.zhou@gmail.com>"]
edition = "2018"

[[bin]]
name = "local"
path = "src/main.rs"

[dependencies]
criterion = "0.2.11"
async-std = "1.1.0"

